name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install project dependencies
        working-directory: ./magnolia-cli
        run: npm install

      - name: Build Vue.js app
        working-directory: ./magnolia-cli
        run: npm run build

      - name: Deploy to EC2
        run: |
          # Add your deployment script here
          # Example: scp -r dist/* ec2-user@54.253.24.35:/workspace/magnolia
