name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

# magnolia-uiの起動
      - name: Install Dependencies
        working-directory: ./magnolia-ui/  # ディレクトリを移動
        run: npm install

      - name: Build and Deploy
        run: |
          # index.jsファイルの実行
          npx node ./magnolia-ui/index.js
# magnolia-cliの起動
      - name: Install Dependencies for vue-app
        working-directory: ./docs/
        run: npm install

      - name: Deploy Vue.js App
        working-directory: ./docs/
        run: |
          # ビルドされたVue.jsアプリをデプロイするコマンド（例えば、GitHub Pagesにデプロイする場合）
          # この部分はデプロイ方法に応じて調整してください
          # 以下はGitHub Pagesにデプロイする例
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git init
          git add .
          git commit -m "Deploy Vue.js App"
          git push --force --quiet "https://${{ GITHUB_TOKEN }}@github.com/yourusername/yourrepo.git" master:gh-pages
